import Head from 'next/head'
import Auth from './../components/Auth'
import { AuthRedirect } from '../hooks/authUser'

export default function Home() {
  AuthRedirect()

  return (
    <div className="flex justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Auth/>
    </div>
  )
}
